import '@public/styles/globals.css';
import { Open_Sans } from 'next/font/google';
import ThemeProvider from '@components/theme-provider';
import Provider from '@components/Provider';

const open_sans = Open_Sans({ subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={open_sans.className}>
          <Provider>  
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
              {children}
            </ThemeProvider>
          </Provider>
      </body>
    </html>
  );
}
